server {
    server_name l2monsters.games www.l2monsters.games;

    root /home/retailx/retailx/frontend;
    index index.html;

    # Frontend static files
    location / {
        try_files $uri $uri/ /index.html;
    }

    location /files/ {
        proxy_pass http://127.0.0.1:3000;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
    }

    # Backend API proxy
    location /api/ {
        proxy_pass http://127.0.0.1:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_cache_bypass $http_upgrade;
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/l2monsters.games-0001/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/l2monsters.games-0001/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot



}
server {
    if ($host = l2monsters.games) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;
    server_name l2monsters.games www.l2monsters.games;
    return 301 https://$server_name$request_uri;


}
